---
# tasks file for apigee-opdk-aws-security-group
- name: Create security group
  ec2_group:
    state: "{{ ec2_group_state | d('present') }}"
    name: '{{ security_group }}'
    description: '{{ security_group_description }}'
    aws_access_key: "{{ aws_access_key|default(lookup('env', 'AWS_ACCESS_KEY_ID')) }}"
    aws_secret_key: "{{ aws_secret_key|default(lookup('env', 'AWS_SECRET_ACCESS_KEY')) }}"
    aws_region: "{{ aws_region|default(lookup('env', 'AWS_REGION'))  }}"
    vpc_id: "{{ vpc_id }}"
    rules: '{{ rules }}'
    rules_egress: '{{ rules_egress }}'
